version: 2

jobs:
  build-and-test:
    docker:
      - image: circleci/php:7.2
    steps:
      - checkout
      - restore_cache:
          keys:
              - composer-v1-{{ checksum "composer.json" }}
              - composer-v1-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor
      - run: composer test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
